name: documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  DOXYGEN_VERSION: '1.9.7'
  DOXYGEN_VER__:   '1_9_7'

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          wget -q https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VER__}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          tar -zxvf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz doxygen-${DOXYGEN_VERSION}/bin/doxygen
          mv doxygen-${DOXYGEN_VERSION}/bin/doxygen /usr/local/bin/
          rm -rf doxygen-${DOXYGEN_VERSION} doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          python3 -m pip install --upgrade pip
          python3 -m pip install -r _docs/requirements.txt
      - name: Build documentation
        run: |
          cd _docs
          python3 build_all_docs.py
          sphinx-build -c . -b html source _build
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _docs/_build
          force_orphan: true
